### ISSUE TITLE
关于fullscreen

### ISSUE THREAD

**Issue by iuzumakin** [ashen-zhao/baisiapp#1]
全屏的那个 用MPMoviePlayer(),然后 点击快进的那个貌似会有些问题耶～

**Comment by ashen-zhao** [comment]
亲，看更新说明哦，全屏播放、快进我都还没更新的

**Comment by iuzumakin** [comment]
是的我知道的，，其实我有在你的基础上 写，然后调用MPMoviePlayer()的全屏 ，，然后就是刚才说的那个问题。。。很期待你的更新呢～

**Comment by ashen-zhao** [comment]
嗯嗯，后续有时间会更新的
